import { Alert, Button, TextInput, View, StyleSheet,ImageBackground,Image,Text} from 'react-native';
const styles = StyleSheet.create({
    backgroundImage:{
  position: 'absolute',
  top: 0,
  left: 0,
  bottom: 0,
  right: 0,
  opacity: 0.3,
},
im1:{
  marginBottom: 10,
  height:40,
  width:40,
  position:"absolute",
  top:20,
  left:10,
},
im2:{
    marginBottom: 10,
    height:40,
    width:40,
    position:"absolute",
    top:40,
    left:10,
  },
  im3:{
    marginBottom: 10,
    height:40,
    width:40,
    position:"absolute",
    top:60,
    left:10,
  },
  im4:{
    marginBottom: 10,
    height:40,
    width:40,
    position:"absolute",
    top:80,
    left:10,
  },
  im5:{
    marginBottom: 10,
    height:40,
    width:40,
    position:"absolute",
    top:100,
    left:10,
  },
  im6:{
    marginBottom: 10,
    height:40,
    width:40,
    position:"absolute",
    top:120,
    left:10,
  },
te:{
  fontSize:40,
  color:'white',
  fontStyle:'italic',
  fontWeight:'bold',
  textShadowColor:'black',
  textShadowRadius:10,
  textDecorationColor:'red',
  marginBottom:500,
  marginLeft:70,

},
te1:{
    fontSize:40,
    color:'white',
    fontStyle:'italic',
    fontWeight:'bold',
    textShadowColor:'black',
    textShadowRadius:10,
    textDecorationColor:'red',
    marginBottom:400,
    marginLeft:70,
  
  },
  te2:{
    fontSize:40,
    color:'white',
    fontStyle:'italic',
    fontWeight:'bold',
    textShadowColor:'black',
    textShadowRadius:10,
    textDecorationColor:'red',
    marginBottom:300,
    marginLeft:70,
  
  },
  te3:{
    fontSize:40,
    color:'white',
    fontStyle:'italic',
    fontWeight:'bold',
    textShadowColor:'black',
    textShadowRadius:10,
    textDecorationColor:'red',
    marginBottom:200,
    marginLeft:70,
  
  },
  te4:{
    fontSize:40,
    color:'white',
    fontStyle:'italic',
    fontWeight:'bold',
    textShadowColor:'black',
    textShadowRadius:10,
    textDecorationColor:'red',
    marginBottom:100,
    marginLeft:70,
  
  },
  te5:{
    fontSize:40,
    color:'white',
    fontStyle:'italic',
    fontWeight:'bold',
    textShadowColor:'black',
    textShadowRadius:10,
    textDecorationColor:'red',
    marginBottom:50,
    marginLeft:70,
  
  },
})